language: ruby
rvm:
  - 2.0.0
services:
  - mongodb
before_install:
  - sudo apt-get install libqtwebkit-dev
  - sudo apt-get install xvfb
before_script:
  - echo "SECRET_TOKEN=`bundle exec rake secret`" > .env
script: xvfb-run rspec